### PR TITLE
feat: Add podAnnotations for deployment 

### PR DESCRIPTION
**Pull request by Anton0C**
Added support for customizable pod annotations in the deployment.yaml and values.yaml files.

- Introduced a new `podAnnotations` field in values.yaml to allow users to define custom annotations for pods.
- Updated deployment.yaml to apply annotations from values.yaml using Helm's templating system.
- Removed redundant `end` statement in tolerations block for cleaner YAML structure.

### CODE REVIEW

**Comment by Anton0C** [comment]
@zakkg3 Please review

**Comment by Anton0C** [comment]
Any updates with it ?

**Comment by zakkg3** [comment]
I have to fix the e2e test and if that passes ill merge this. I guess in the next days I hope I find the time for this. 
sorry for the delay.

**Comment by Anton0C** [comment]
> I have to fix the e2e test and if that passes ill merge this. I guess in the next days I hope I find the time for this. sorry for the delay.

Super good. Thank you.

**Comment by zakkg3** [comment]
thanks for the pr. 
merging all here https://github.com/zakkg3/ClusterSecret/pull/143

**Comment by zakkg3** [comment]
BTW the e2e test are failing cause the was some changes on the chart without bumping the chart version. will fix this all on the fix-all pr

**Pull request merged**
