### PR TITLE
feat: migrating to ClusterScope CRD

### PR DESCRIPTION
**Pull request by axel7083**
Fix: https://github.com/zakkg3/ClusterSecret/issues/91

Admin privilege are required to setup Cluster Secret CRD since it requires a ClusterRole. Therefore there is not real reason to keep the resource namespaced when it has side effects on all namespaces.

Making its scope cluster wide makes more sense.

### CODE REVIEW

**Comment by axel7083** [comment]
@zakkg3 if you agree and think this is the appropriate direction to take, we can create a new milestone for a future release ?

**Comment by axel7083** [comment]
@zakkg3 I still think that would be a good idea !

> I also fixed the github actions that needed some update

**Comment by toabi** [comment]
While evaluating this project for easier secret handling, this PR is keeping me from deployment. :)

**Review by zakkg3 — APPROVED** [review]

**Comment by toabi** [comment]
Cool that this was merged, but it looks like there's no new container released yet?

**Pull request merged**
