### PR TITLE
Overall stability improvements and code quality

### PR DESCRIPTION
**Pull request by axel7083**
Fixes: 
- Preventing exception when secret does not exist in on_field_data

Sometime, in specific case, the secret could have been manually or accidentally deleted.
The `on_field_data` is suppose to update the value, but sometime, the previous resource no longer exist. And therefore need to be re-created. Calling `replace_namespaced_secret` will raise an `kubernetes.client.ApiException` (404), and will prevent the code to execute properly. Leading to many errors.

Checking the secret still exist, allows to use `create_namespaced_secret` instead of `replace_namespaced_secret`.

### CODE REVIEW

**Comment by zakkg3** [comment]
Thanks for this PR.
I have to test it locally and come back yo you. 
In the meantime this one is not backwards compatible.  I mean if there is already secrets synced by clustermonkey they will not have introduced annotation.
We may want to come with a script / procedure on how to upgrade...

**Comment by axel7083** [comment]
> Many thanks for this valuable PR. I have to test it locally and come back yo you.
> 
> We have to discuss, what do we do when the secret exist already. Ofc a not catch exception is bad. maybe rise an error there. But not sure if replace the secret is the best approach. we could cause a loss of valuable information by this. Maybe we can add a config variable "REEPLACE_EXISTING", by default false. in the helm chart injecting this as an envar on the deployment (in the deploy.yamls as-well). So if this is flase, we rise error and do nothing, if this is true we do what your code does: replace with updated annotations. With this we can also give the chance to upgrade existing clustermonkey installations by enableing this option.
> 
> what do you think ?

Yeah I like the idea of having a config env for REPLACE_EXISTING !

**Comment by zakkg3** [comment]
> 

great so. can you implement this? 🙏 
it should be relatively easy for you.

we have another pr that needs rebuild image. 
  - add liveness 
  - add differench archs

once we merge all of them including this one i ll release 0.1.0

**Comment by axel7083** [comment]
> i dont know if its clear enough i will just paste the whole helper.py here: you can copy paste commit :) its tested on kubernetes 1.27.1
> 
> ```python
> import logging
> from typing import Optional, Dict, Any, List
> 
> import kopf
> import re
> from kubernetes import client
> import os
> from datetime import datetime
> 
> from kubernetes.client import CoreV1Api
> 
> from consts import CREATE_BY_ANNOTATION, LAST_SYNC_ANNOTATION, \
>     VERSION_ANNOTATION
> 
> 
> def get_version() -> str:
>     return os.getenv('CLUSTER_SECRET_VERSION', '0')
> 
> 
> def get_replace_existing() -> bool:
>     replace_existing = os.getenv('REPLACE_EXISTING', 'false')
>     return replace_existing.lower() == 'true'
> 
> 
> def patch_clustersecret_status(
>         logger: logging.Logger,
>         namespace: str,
>         name: str,
>         new_status,
>         v1: Optional[CoreV1Api] = None
> ):
>     """Patch the status of a given clustersecret object
>     """
>     v1 = v1 or client.CustomObjectsApi()
> 
>     group = 'clustersecret.io'
>     version = 'v1'
>     plural = 'clustersecrets'
> 
>     # Retrieve the clustersecret object
>     clustersecret = v1.get_namespaced_custom_object(
>         group=group,
>         version=version,
>         namespace=namespace,
>         plural=plural,
>         name=name
>     )
> 
>     # Update the status field
>     clustersecret['status'] = new_status
>     logger.debug(f'Updated clustersecret manifest: {clustersecret}')
> 
>     # Perform a patch operation to update the custom resource
>     v1.patch_namespaced_custom_object(
>         group=group,
>         version=version,
>         namespace=namespace,
>         plural=plural,
>         name=name,
>         body=clustersecret
>     )
> 
> 
> def get_ns_list(
>         logger: logging.Logger,
>         body: Dict[str, Any],
>         v1: Optional[CoreV1Api] = None
> ) -> List[str]:
>     """Returns a list of namespaces where the secret should be matched
>     """
>     v1 = v1 or client.CoreV1Api()
> 
>     matchNamespace = '*' if 'matchNamespace' not in body else body['matchNamespace']
>     logger.debug(f'Matching namespaces: {matchNamespace}')
>     
>     if matchNamespace is None:  # if delted key (issue 26)
>         matchNamespace = '*'
>     
>     try:
>         avoidNamespaces = body.get('avoidNamespaces')
>     except KeyError:
>         avoidNamespaces = ''
>         logger.debug("not avoiding namespaces")
> 
>     nss = v1.list_namespace().items
>     matchedns = []
>     avoidedns = []
> 
>     for matchns in matchNamespace:
>         for ns in nss:
>             if re.match(matchns, ns.metadata.name):
>                 matchedns.append(ns.metadata.name)
>                 logger.debug(f'Matched namespaces: {ns.metadata.name} match pattern: {matchns}')
>     if avoidNamespaces:
>         for avoidns in avoidNamespaces:
>             for ns in nss:
>                 if re.match(avoidns, ns.metadata.name):
>                     avoidedns.append(ns.metadata.name)
>                     logger.debug(f'Skipping namespaces: {ns.metadata.name} avoid pattern: {avoidns}')  
>     # purge
>     for ns in matchedns.copy():
>         if ns in avoidedns:
>             matchedns.remove(ns)
> 
>     return matchedns
> 
> 
> def read_data_secret(
>         logger: logging.Logger,
>         name: str,
>         namespace: str,
>         v1: Optional[CoreV1Api] = None
> ):
>     """Gets the data from the 'name' secret in namespace
>     """
>     data={}
>     logger.debug(f'Reading {name} from ns {namespace}')
>     try: 
>         secret = v1.read_namespaced_secret(name, namespace)
> 
>         logger.debug(f'Obtained secret {secret}')
>         data = secret.data
>     except client.exceptions.ApiException as e:
>         logger.error('Error reading secret')
>         logger.debug(f'error: {e}')
>         if e == "404":
>             logger.error(f"Secret {name} in ns {namespace} not found!")
>         raise kopf.TemporaryError("Error reading secret")
>     return data
> 
> 
> def delete_secret(
>         logger: logging.Logger,
>         namespace: str,
>         name: str,
>         v1: Optional[CoreV1Api] = None
> ):
>     """Deletes a given secret from a given namespace
>     """
>     v1 = v1 or client.CoreV1Api()
> 
>     logger.info(f'deleting secret {name} from namespace {namespace}')
>     try:
>         v1.delete_namespaced_secret(name,namespace)
>     except client.rest.ApiException as e:
>         if e.status == 404:
>             logger.warning(f"The namespace {namespace} may not exist anymore: Not found")
>         else:
>             logger.warning(" Something weird deleting the secret")
>             logger.debug(f"details: {e}")
> 
> 
> def secret_exists(
>         logger: logging.Logger,
>         name: str,
>         namespace: str,
>         v1: Optional[CoreV1Api] = None
> ):
>     return secret_metadata(
>         logger=logger,
>         name=name,
>         namespace=namespace,
>         v1=v1,
>     ) is not None
> 
> 
> def secret_metadata(
>         logger: logging.Logger,
>         name: str,
>         namespace: str,
>         v1: Optional[CoreV1Api] = None
> ) -> Optional[Dict[str, str]]:
>     v1 = v1 or client.CoreV1Api()
> 
>     try:
>         secret = v1.read_namespaced_secret(name, namespace)
>         return secret.metadata
>     except client.exceptions.ApiException as e:
>         if e.status == 404:
>             return None
>         logger.warning(f'Cannot read the secret {e}.')
>         raise kopf.TemporaryError(f'Error reading secret {e}')
> 
> 
> def sync_secret(
>         logger: logging.Logger,
>         namespace: str,
>         body: Dict[str, Any],
>         v1: Optional[CoreV1Api] = None
> ):
>     """Creates a given secret on a given namespace
>     """
>     v1 = v1 or client.CoreV1Api()
> 
>     if 'metadata' not in body:
>         raise kopf.TemporaryError("Metadata is required.")
> 
>     if 'name' not in body['metadata']:
>         raise kopf.TemporaryError("Property name is missing in metadata.")
> 
>     sec_name = body['metadata']['name']
> 
>     if 'data' not in body:
>         raise kopf.TemporaryError("Property data is missing.")
> 
>     data = body['data']
> 
>     if 'valueFrom' in data:
>         if len(data.keys()) > 1:
>             logger.error('Data keys with ValueFrom error, enable debug for more details')
>             logger.debug(f'keys: {data.keys()}  len {len(data.keys())}')
>             raise kopf.TemporaryError("ValueFrom can not coexist with other keys in the data")
>             
>         try:
>             ns_from = data['valueFrom']['secretKeyRef']['namespace']
>             name_from = data['valueFrom']['secretKeyRef']['name']
>             # key_from = data['ValueFrom']['secretKeyRef']['name']
>             # to-do specifie keys. for now. it will clone all.
>             logger.debug(f'Taking value from secret {name_from} from namespace {ns_from} - All keys')
>             data = read_data_secret(logger, name_from, ns_from, v1)
>         except KeyError:
>             logger.error (f'ERROR reading data from remote secret, enable debug for more details')
>             logger.debug (f'Deta details: {data}')
>             raise kopf.TemporaryError("Can not get Values from external secret")
> 
>     logger.debug(f'Going to create with data: {data}')
>     secret_type = 'Opaque'
>     if 'type' in body:
>         secret_type = body['type']
> 
>     body = client.V1Secret()
>     body.metadata = create_secret_metadata(name=sec_name, namespace=namespace)
>     body.type = secret_type
>     body.data = data
>     # kopf.adopt(body)
>     logger.info(f"cloning secret in namespace {namespace}")
> 
>     try:
>         # Get metadata from secrets (if exist)
>         metadata = secret_metadata(logger, name=sec_name, namespace=namespace)
> 
>         # If nothing returned, the secret does not exist, creating it then
>         if metadata is None:
>             logger.info(f'Using create_namespaced_secret')
>             logger.debug(f'response is {v1.create_namespaced_secret(namespace, body)}')
>             return
>         
>         if metadata.annotations is None:
>             logger.info("secret `{sec_name}` exist but it does not have annotations, so is not managed by ClusterSecret")
> 
>             # If we should not overwrite existing secrets
>             if not get_replace_existing():
>                 logger.info(f"secret `{sec_name}` will not be replaced. You can enforce this by setting env REPLACE_EXISTING to true.")
>                 return
>         else:
>             if metadata.annotations.get(CREATE_BY_ANNOTATION) is None:
>                 logger.error(f"secret `{sec_name}` already exist in namespace '{namespace}' and is not managed by ClusterSecret")
> 
>                 if not get_replace_existing():
>                     logger.info(f"secret `{sec_name}` will not be replaced. You can enforce this by setting env REPLACE_EXISTING to true.")
>                     return
> 
>             logger.info(f'Reeplacing secret {sec_name}')
>             v1.replace_namespaced_secret(
>                 name=sec_name,
>                 namespace=namespace,
>                 body=body
>             )
>     except client.rest.ApiException as e:
>         logger.error(f'Can not create a secret, it is base64 encoded? enable debug for details')
>         logger.debug(f'data: {data}')
>         logger.debug(f'Kube exception {e}')
> 
> 
> def create_secret_metadata(name: str, namespace: str) -> client.V1ObjectMeta:
>     return client.V1ObjectMeta(
>         name=name,
>         namespace=namespace,
>         annotations={
>             CREATE_BY_ANNOTATION: "ClusterSecrets",
>             VERSION_ANNOTATION: get_version(),
>             LAST_SYNC_ANNOTATION: datetime.now().isoformat()
>         }
>     )
>     ```
> ```

done

**Comment by zakkg3** [comment]
can not see any more bugs.
still pending adding the vars to the helm chart and adding a reference in values files 
and also updating documentation.

but i will do this in a next PR. thanks again!

**Review by zakkg3 — APPROVED** [review]

**Comment by zakkg3** [comment]
I need maintainers.
to IE: review: https://github.com/zakkg3/ClusterSecret/pull/87

**Pull request merged**
