### PR TITLE
fix linter flake8 and unit tests

### PR DESCRIPTION
**Pull request by axel7083**
## Linter

I added a `setup.cfg` file with **a lot** of ignore for the linter since [wemake-python-styleguide]() is very very strict and we do not have time to re-write all the python code.

So to keep the tests green I fix some of the warning, and ignore most of them.

## Unit tests

I added a `/src/tests` folder with some unit tests. The goal being to add enough to have a better testing of the operator.

### CODE REVIEW

**Comment by axel7083** [comment]
This PR is kinda big even if there is not really new features. So if you have some time to tests it @zakkg3 , I would appreciate :) !

**Comment by zakkg3** [comment]
Bug 
```shell
with url: /api/v1/namespaces (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x10f948130>: Failed to establish a new connection: [Errno 61] Connection refused\
```

How to reproduce:

1- Update kind to latest 
   `brew upgrade kind` for mac
   `apt intall kind` or equivalent
 this pulls kubernetes 1.27.3 as for today.

2- created a new kind cluster with 
`make test-env`

3- apply the rbac and crd yamls. 
     `kubectl apply -f yaml/00_rbac.yaml`
      `kubectl apply -f yaml/01_crd.yaml`

4- run the operator locally & verbose:
  `make dev-run`

5- apply basic object
   k apply -f yaml/Object_example/obj.yaml

**Comment by axel7083** [comment]
> Bug
> 
> ```shell
> with url: /api/v1/namespaces (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x10f948130>: Failed to establish a new connection: [Errno 61] Connection refused\
> ```
> 
> How to reproduce:
> 
> 1- Update kind to latest `brew upgrade kind` for mac `apt install kind` or equivalent this pulls kubernetes 1.27.3 as for today.
> 
> 2- created a new kind cluster with `make test-env`
> 
> 3- apply the rbac and crd yamls. `kubectl apply -f yaml/00_rbac.yaml` `kubectl apply -f yaml/01_crd.yaml`
> 
> 4- run the operator locally & verbose: `make dev-run` (this is commited on master). in the branch here use `kopf run ./src/handlers.py --verbose -A`
> 
> 5- apply basic object k apply -f yaml/Object_example/obj.yaml

It mays appear we need to use

```
from kubernetes import config

config.load_incluster_config()
```

I will take a deeper look

**Comment by axel7083** [comment]
> Bug
> 
> ```shell
> with url: /api/v1/namespaces (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x10f948130>: Failed to establish a new connection: [Errno 61] Connection refused\
> ```
> 
> How to reproduce:
> 
> 1- Update kind to latest `brew upgrade kind` for mac `apt install kind` or equivalent this pulls kubernetes 1.27.3 as for today.
> 
> 2- created a new kind cluster with `make test-env`
> 
> 3- apply the rbac and crd yamls. `kubectl apply -f yaml/00_rbac.yaml` `kubectl apply -f yaml/01_crd.yaml`
> 
> 4- run the operator locally & verbose: `make dev-run` (this is commited on master). in the branch here use `kopf run ./src/handlers.py --verbose -A`
> 
> 5- apply basic object k apply -f yaml/Object_example/obj.yaml

Should be fixed

**Comment by zakkg3** [comment]
is this running on your local cluster??

`kubernetes.config.config_exception.ConfigException: Service host/port is not set.`

if we create a v1 locally (so revert the v1 being global) that fixes the first bug. didnt try yet for the on_delete....

**Comment by zakkg3** [comment]
> is this running on your local cluster??
> 
> `kubernetes.config.config_exception.ConfigException: Service host/port is not set.`
> 
> if we create a v1 locally (so revert the v1 being global) that fixes the first bug. didnt try yet for the on_delete....

this is running in debug mode. 
where environment variables KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT are not set...

**Comment by zakkg3** [comment]
on os_utils add:

```python
def get_in_cluster():
    """
    weather we are running in cluster or outside (debug mode.)
    """ 
    return os.getenv('KUBERNETES_SERVICE_HOST', '0') != "0"
```

on handlers line 15 replace:
```python
if get_in_cluster():
    # Loading kubeconfig
    config.load_incluster_config()
else:
    config.load_kube_config()
```

**Comment by zakkg3** [comment]
the deleting problem is related with the named paramaters.
there is something wrong there
reeplace this on handlers:

```
@kopf.on.delete(
    group='clustersecret.io',
    version='v1',
    kind='clustersecrets',
)
```
with this
```
@kopf.on.delete('clustersecret.io', 'v1', 'clustersecrets')
```

solved the problem.

**Comment by zakkg3** [comment]
maybe we can use the already merged conformance tests cherry picking d8b24b5f92063059b8bf1f78764f0d0b981afd4d ?

**Comment by axel7083** [comment]
> maybe we can use the already merged conformance tests cherry picking [d8b24b5](https://github.com/zakkg3/ClusterSecret/commit/d8b24b5f92063059b8bf1f78764f0d0b981afd4d) ?

You mean including the unit tests in the e2e tests workflow ?

**Comment by zakkg3** [comment]
> > maybe we can use the already merged conformance tests cherry picking [d8b24b5](https://github.com/zakkg3/ClusterSecret/commit/d8b24b5f92063059b8bf1f78764f0d0b981afd4d) ?
> 
> You mean including the unit tests in the e2e tests workflow ?

I mean use the automated tests for this pr. If you cherry pick that commit or rebase with master you should trigger those.

**Comment by axel7083** [comment]
> > > maybe we can use the already merged conformance tests cherry picking [d8b24b5](https://github.com/zakkg3/ClusterSecret/commit/d8b24b5f92063059b8bf1f78764f0d0b981afd4d) ?
> > 
> > 
> > You mean including the unit tests in the e2e tests workflow ?
> 
> I mean use the e2e for this pr. If you cherry pick that commit or rebase with master you should trigger those.

I made an empty commit to trigger the action.

**Review by zakkg3 — APPROVED** [review]

**Comment by zakkg3** [comment]
LGTM

**Comment by zakkg3** [comment]
if you use slack [https://clustersecret.slack.com/](https://join.slack.com/t/clustersecret/shared_invite/zt-19ljb3tr8-lnMkzPkA1_BItpHYyrJVmA)

**Pull request merged**
